apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-js-server
spec:
  replicas: 3  # Set the desired number of replicas
  selector:
    matchLabels:
      app: node-js-server
  template:
    metadata:
      labels:
        app: node-js-server
    spec:
      containers:
        - name: node-js-server
          image: mihailo34/simple-nodejs-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName  # Set the environment variable with the worker node's name

