apiVersion: v1
kind: Service
metadata:
  name: node-js-service
spec:
  selector:
    app: node-js-server
  ports:
    - protocol: TCP
      port: 80      # Port on the Service
      targetPort: 80  # Port on the Pods
  type: ClusterIP   # Use ClusterIP if you want an internal service

